import type { Metadata } from "next";import "./globals.css";
import './globals.css'
export const metadata: Metadata = {
  title: "paybox dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
